### ISSUE TITLE
Fehler beim Kompilieren

### ISSUE THREAD

**Issue by lety2000** [HerrRiebmann/Caravan_Leveler#2]
Hallo, 

ich bin gerade dabei, den Leveler nachzubauen. Vielen Dank für die Dokumentation des Projektes! Beim Kompilieren bei treten einige Fehler auf:

 C:\Users\***\Documents\Arduino\Caravan_Leveler-main\Caravan_Leveler\Caravan_Leveler.ino: In function 'void setup()':

Caravan_Leveler:51:3: error: 'SerialBegin' was not declared in this scope

C:\Users\***\Documents\Arduino\Caravan_Leveler-main\Caravan_Leveler\Caravan_Leveler.ino:51:3: note: suggested alternative: 'Serial2'

Caravan_Leveler:52:3: error: 'Adxl345Begin' was not declared in this scope

Caravan_Leveler:53:3: error: 'EepromBegin' was not declared in this scope

C:\Users\***\Documents\Arduino\Caravan_Leveler-main\Caravan_Leveler\Caravan_Leveler.ino:53:3: note: suggested alternative: 'uartBegin'

Caravan_Leveler:55:3: error: 'LoadData' was not declared in this scope

Caravan_Leveler:57:3: error: 'SpiffsBegin' was not declared in this scope

C:\Users\***\Documents\Arduino\Caravan_Leveler-main\Caravan_Leveler\Caravan_Leveler.ino:57:3: note: suggested alternative: 'timerBegin'

Caravan_Leveler:58:3: error: 'WiFiBegin' was not declared in this scope

C:\Users\***\Documents\Arduino\Caravan_Leveler-main\Caravan_Leveler\Caravan_Leveler.ino:58:3: note: suggested alternative: 'timerBegin'

Caravan_Leveler:59:3: error: 'setupOTA' was not declared in this scope

C:\Users\***\Documents\Arduino\Caravan_Leveler-main\Caravan_Leveler\Caravan_Leveler.ino:59:3: note: suggested alternative: 'setup'

C:\Users\***\Documents\Arduino\Caravan_Leveler-main\Caravan_Leveler\Caravan_Leveler.ino: In function 'void loop()':

Caravan_Leveler:75:7: error: 'getLevel' was not declared in this scope

C:\Users\***\Documents\Arduino\Caravan_Leveler-main\Caravan_Leveler\Caravan_Leveler.ino:75:7: note: suggested alternative: 'geteuid'

Mehrere Bibliotheken wurden für "WiFi.h" gefunden

 Benutzt: C:\Users\***\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\WiFi

 Nicht benutzt: C:\Program Files (x86)\Arduino\libraries\WiFi

exit status 1

'SerialBegin' was not declared in this scope

Leider kann ich im Netz nichts Konkretes finden, was mir weiterhelfen würde.
Ich habe den Ordner "Data" Sketch Data Upload bereits auf den ESP hochgeladen. 
Können Sie mir sagen, woran es hakt?
Vielen Dank!

**Comment by HerrRiebmann** [comment]
Hi,

das sieht mir sehr danach aus, als sind nicht alle Dateien aus dem Ordner kopiert worden.
Die `Caravan_Leveler.ino` ist nur die "_Start_"-Datei. Alle weiteren *.ino-Dateien müssen ebenfalls in dem Verzeichnis liegen.
Und der Ordner "/data" ist notwendig, damit im nächsten Schritt die Dateien für die Webseite auf den ESP übertragen werden können.
Das habe ich dann her beschrieben:
https://github.com/HerrRiebmann/Caravan_Leveler?tab=readme-ov-file#SPIFFS-Upload

**Comment by lety2000** [comment]
Das Problem lag an mir...die zusätzlichen .ino Dateien lagen tatsächlich im falschen Ordner. Jetzt hat es geklappt, ich kann eine Verbindung zum ESP herstellen. 
Vielen Dank für die schnelle Antwort!
